language: node_js

sudo: true

node_js:
    - "8.4"

cache:
    yarn: true


install:
    - yarn --pure-lockfile --ignore-scripts
    - sudo apt-get install graphicsmagick

script:
    - yarn run build
    - yarn run test

deploy:
    provider: pages
    local_dir: ./dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master


notifications:
    email: false