language: node_js

sudo: false

node_js:
    - "6.10"

cache:
    yarn: true


install:
    - yarn --pure-lockfile --ignore-scripts

script:
    - yarn run build
    - ls -l dist

deploy:
    provider: pages
    local_dir: ./dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master


notifications:
    email: false